copywriter_whatsApp_task:
  description: >
    Crie uma mensagem persuasiva e curta para a campanha de {tipo_campanha} da {nome_loja}, que opera no segmento de {segmento}.
    A mensagem deve ser personalizada para o público-alvo {publico_alvo}, utilizando um tom de voz {tom_voz}.
    
    Se for uma campanha de Giftback, destaque o valor do desconto de {{giftback_amount}}, o código {{giftback_code}} e a data de expiração {{giftback_expiry_date}}.

    Se for uma campanha de data comemorativa, leve em conta a data de {data_comemorativa}.

    Se for uma campanha de lançamento de produto, destaque o novo produto {nome_produto}, destacando suas principais características: {descricao_produto}.

    Se for uma campanha de lançamento de coleção, destaque a nova coleção {nome_colecao}, ressaltando suas principais tendências e exclusividades: {descricao_colecao}.

    Se for uma campanha de aniversário de cliente, ofereça uma felicitação personalizada e destaque o benefício ou presente especial oferecido.

    Certifique-se de que a mensagem seja clara, impactante e otimizada para o disparo via WhatsApp. **É essencial que a mensagem contenha quebras de linha adequadas para garantir boa visualização no WhatsApp.**
    Não utilize hashtags, pois não é uma prática comum no WhatsApp.
    A mensagem deve seguir a estrutura recomendada: cabeçalho que chame atenção, corpo que destaque o benefício ou produto, uma linha de urgência, e uma chamada clara para ação.
    Utilize os placeholders corretamente e adapte o texto de acordo com as melhores práticas de copywriting.

  expected_output: |
    - Deve conter até 450 caracteres.
    - A mensagem deve ser persuasiva, clara e otimizada para disparo via WhatsApp.
    - **A formatação deve incluir quebras de linha adequadas para WhatsApp.**
    - Alinhamento com o tom de voz {tom_voz} e consideração do público-alvo {publico_alvo}.
    - Utilização correta dos placeholders da mensagem.

