copywriter_data_comemorativa_task:
  description: >
    "Criar mensagens curtas e impactantes para a campanha de {objetivo_campanha} da {nome_loja}, uma loja do segmento de {segmento}."
    " As mensagens devem ser personalizadas para o público-alvo {publico_alvo}, adaptando o tom de voz {tom_de_voz} e utilizando as variáveis disponíveis de forma relevante."
    " Dependendo do tipo de campanha {tipo_campanha} – como 'Data Comemorativa', 'Lançamento de produto' ou 'Liquidação' – a mensagem deve ser ajustada conforme as práticas recomendadas para cada contexto."
  expected_output: |
    Uma mensagem de até 350 caracteres, persuasiva e otimizada para disparos em massa via WhatsApp.
    A mensagem deve ser personalizada e adaptada com base nas variáveis fornecidas, como {{client_first_name}}, {{last_purchase_date}}, {{giftback_code}}, entre outras.
    As variáveis da Zoppy devem permanecer no formato de placeholder (por exemplo, {{client_first_name}}) para que sejam substituídas por outra parte do sistema posteriormente.
    Utilize o tom de voz {tom_de_voz} e certifique-se de que a mensagem ressoe com o público-alvo {publico_alvo} e o objetivo da campanha ({objetivo_campanha}).
    Ajuste o conteúdo para maximizar o impacto de acordo com o tipo de campanha {tipo_campanha}.
    Lembre-se de com as variaveis da Zoppy sempre ultilizar duas chaves {{}} para que o sistema possa substituir posteriormente.
    Foco nas quebras de linha, pois elas são importantes para a formatação da mensagem no WhatsApp.

    ### Estrutura de uma Mensagem de Campanha de WhatsApp:

    Cada mensagem deve seguir a estrutura abaixo para garantir clareza e eficácia:

    - **Cabeçalho**: Uma linha inicial que capte a atenção do cliente. Deve ser personalizada (por exemplo, "Atenção, {{client_first_name}}! 🔥") e pode usar emojis para criar uma conexão emocional imediata.
    
    - **Corpo**: A parte principal da mensagem que explica o benefício ou a oferta. Deve ser conciso, claro e direto ao ponto (por exemplo, "Nossa grande liquidação começou! Descontos de até 70% em itens selecionados."). Utilize quebras de linha para facilitar a leitura no WhatsApp.

    - **Urgência**: Inclua uma linha que crie um senso de urgência para motivar uma ação rápida (por exemplo, "Corra, pois é por tempo limitado!").

    - **Call to Action (CTA)**: Sempre o último item da mensagem, instruindo o cliente sobre o que fazer a seguir. Deve ser claro e fácil de entender, com um link para ação direta (por exemplo, "Compre já: {{store_url}}").

    Lembre-se de deixar o CTA por último para que o cliente saiba exatamente o que fazer após ler a mensagem.

    Lembre-se de com as variaveis da Zoppy sempre ultilizar duas chaves {{}} para que o sistema possa substituir posteriormente.

    Vou lhe fornecer alguns tipos de modelos de mensagens validados para você se inspirar parar gerar diversos tipos de campanhas.
    Exemplos de mensagens para diferentes tipos de campanha:

  