copywriter_giftback_task:
  description: >
    Crie uma mensagem persuasiva e curta para a campanha de Giftback com o objetivo de: {objetivo_campanha} da {nome_loja}, que opera no segmento de {segmento}.
    A mensagem deve ser personalizada para o público-alvo {publico_alvo}, utilizando um tom de voz {tom_voz}.
    O foco da campanha é no uso do Giftback, então a mensagem deve destacar o valor do desconto {{giftback_amount}}, o código {{giftback_code}} e a data de expiração {{giftback_expiry_date}}.
    Certifique-se de que a mensagem seja clara, impactante, e otimizada para disparo via WhatsApp. Não utilize hashtags, pois não é uma prática comum no WhatsApp.
    A mensagem deve seguir a estrutura recomendada: cabeçalho que chame atenção, corpo que destaque o benefício do Giftback, uma linha de urgência, e uma chamada clara para ação.
    Utilize os placeholders de modelo de mensagem corretamente (ex.: Olá, {{client_first_name}}) e adapte o texto de acordo com as melhores práticas de copywriting.
    Tome cuidado para não inventar informações sobre a promoção, utilize apenas os inputs fornecidos.
  
  expected_output: |
    - Deve conter até 450 caracteres.
    - A mensagem deve ser persuasiva, clara e otimizada para disparo via WhatsApp.
    - Formatação adequada para WhatsApp com quebras de linha.
    - Alinhamento com o tom de voz {tom_voz} e consideração do público-alvo {publico_alvo}.
    - Utilização correta dos placeholders da mensagem.
    - A mensagem deve possuir as seguintes seções:
        - **Cabeçalho**: Personalize para chamar atenção imediatamente (Ex.: "Oi, {{client_first_name}}! Seu Giftback está esperando!").
        - **Corpo**: Destaque o benefício do Giftback e como usá-lo (Ex.: "Ganhe {{giftback_amount}} de desconto com o código {{giftback_code}}").
        - **Urgência**: Crie um senso de urgência para incentivar ação rápida (Ex.: "Seu Giftback expira em {{giftback_expiry_date}}!").
        - **Call to Action (CTA)**: Finalize com uma instrução clara (Ex.: "Compre agora: {{store_url}}").


copywright_data_comemorativa_task:
  description: >
     Crie uma mensagem persuasiva e curta para a campanha de promoção por data comemorativa com o objetivo de: {objetivo_campanha} da {nome_loja}, que opera no segmento de {segmento}.
     A mensagem deve ser personalizada para o público-alvo {publico_alvo}, utilizando um tom de voz {tom_voz} específico.
     A copy deve levar em conta a data comemorativa selecionada, que é a {data_comemorativa}, e incentivar a compra.
     Certifique-se de que a mensagem seja clara, impactante, e otimizada para o disparo via WhatsApp. Não utilize hashtags, pois não é uma prática comum no WhatsApp.
     A mensagem deve seguir a estrutura recomendada: cabeçalho que capte atenção, corpo que destaque a promoção estabelecida, uma linha de urgência, e uma chamada para ação clara.
     Utilize os placeholders de modelo de mensagem variáveis corretamente (ex.: Olá, {{client_first_name}}) e adapte o texto de acordo com as melhores práticas de copywriting.
     Tome cuidado para não inventar informações sobre a promoção, utilize apenas os inputs fornecidas.
  
  expected_output: |
    - Deve conter até 450 caracteres.
    - A mensagem deve ser persuasiva, clara, e otimizada para disparo via WhatsApp.
    - Formatação adequada para WhatsApp com quebras de linha.
    - Alinhamento com o tom de voz {tom_voz} e consideração do público-alvo {publico_alvo}.
    - Utilização correta dos placeholders da mensagem.
    - A mensagem deve possuir as seguintes seções:
        - **Cabeçalho**: Personalize para chamar atenção imediatamente (Ex.: "Oi, {{client_first_name}}! Seu Giftback está esperando!").
        - **Corpo**: Destaque os benefícios do Giftback e explique como usá-lo (Ex.: "Aproveite {{giftback_amount}} de desconto usando o código {{giftback_code}}").
        - **Urgência**: Crie um senso de urgência para incentivar ação rápida (Ex.: "Atenção! Seu Giftback expira em {{giftback_expiry_date}}!").
        - **Call to Action (CTA)**: Finalize com uma instrução clara para ação (Ex.: "Aproveite agora: {{store_url}}").

copywriter_lancamento_produto_task:
  description: >
    Crie uma mensagem persuasiva e curta para a campanha de lançamento do produto {nome_produto} da {nome_loja}, que opera no segmento de {segmento}.
    A mensagem deve ser personalizada para o público-alvo {publico_alvo}, utilizando um tom de voz {tom_voz}.
    O foco da campanha é o novo produto {nome_produto}, então a mensagem deve destacar os principais benefícios e características da {descricao_produto}.
    Certifique-se de que a mensagem seja clara, impactante, e otimizada para disparo via WhatsApp. Não utilize hashtags, pois não é uma prática comum no WhatsApp.
    A mensagem deve seguir a estrutura recomendada: cabeçalho que chame atenção, corpo que destaque o lançamento do produto e suas vantagens, uma linha de urgência, e uma chamada clara para ação.
    Utilize os placeholders corretamente e adapte o texto de acordo com as melhores práticas de copywriting.
    Tome cuidado para não inventar informações sobre o produto, utilize apenas os inputs fornecidos.

  expected_output: |
    - Deve conter até 450 caracteres.
    - A mensagem deve ser persuasiva, clara e otimizada para disparo via WhatsApp.
    - Formatação adequada para WhatsApp com quebras de linha.
    - Alinhamento com o tom de voz {tom_voz} e consideração do público-alvo {publico_alvo}.
    - Utilização correta dos placeholders da mensagem.
    - A mensagem deve possuir as seguintes seções:
        - **Cabeçalho**: Personalize para chamar atenção imediatamente (Ex.: "Novo na {nome_loja}: {nome_produto}!").
        - **Corpo**: Destaque as principais características e benefícios (Ex.: "Confira o {nome_produto}, {descricao_produto}.").
        - **Urgência**: Crie um senso de urgência (Ex.: "Garanta o seu antes que acabe!").
        - **Call to Action (CTA)**: Finalize com uma instrução clara (Ex.: "Veja agora: {{store_url}}").


copywriter_lancamento_colecao_task:
  description: >
    Crie uma mensagem persuasiva e curta para a campanha de lançamento da coleção {nome_colecao} da {nome_loja}, que opera no segmento de {segmento}.
    A mensagem deve ser personalizada para o público-alvo {publico_alvo}, utilizando um tom de voz {tom_voz}.
    O foco da campanha é o lançamento da nova coleção {nome_colecao}, então a mensagem deve destacar as principais tendências e exclusividades da {descricao_colecao}.
    Certifique-se de que a mensagem seja clara, impactante, e otimizada para disparo via WhatsApp. Não utilize hashtags, pois não é uma prática comum no WhatsApp.
    A mensagem deve seguir a estrutura recomendada: cabeçalho que chame atenção, corpo que destaque a coleção, uma linha de urgência, e uma chamada clara para ação.
    Utilize os placeholders corretamente e adapte o texto de acordo com as melhores práticas de copywriting.
    Tome cuidado para não inventar informações sobre a coleção, utilize apenas os inputs fornecidos.

  expected_output: |
    - Deve conter até 450 caracteres.
    - A mensagem deve ser persuasiva, clara e otimizada para disparo via WhatsApp.
    - Formatação adequada para WhatsApp com quebras de linha.
    - Alinhamento com o tom de voz {tom_voz} e consideração do público-alvo {publico_alvo}.
    - Utilização correta dos placeholders da mensagem.
    - A mensagem deve possuir as seguintes seções:
        - **Cabeçalho**: Personalize para chamar atenção imediatamente (Ex.: "Chegou a nova coleção {nome_colecao}!").
        - **Corpo**: Destaque as exclusividades da coleção (Ex.: "Confira nossas peças de {descricao_colecao}.").
        - **Urgência**: Crie um senso de urgência (Ex.: "Não perca! As peças são limitadas.").
        - **Call to Action (CTA)**: Finalize com uma instrução clara (Ex.: "Compre agora: {{store_url}}").

copywriter_aniversario_cliente_task:
  description: >
    Crie uma mensagem personalizada e curta para a campanha de aniversário de cliente da {nome_loja}, que opera no segmento de {segmento}.
    A mensagem deve ser adaptada ao público-alvo {publico_alvo} e utilizar um tom de voz {tom_voz}.
    O foco da campanha é celebrar o aniversário do cliente, oferecendo um benefício ou presente, então a mensagem deve ser calorosa e incentivadora.
    Certifique-se de que a mensagem seja clara, amigável, e otimizada para disparo via WhatsApp. Não utilize hashtags, pois não é uma prática comum no WhatsApp.
    A mensagem deve seguir a estrutura recomendada: cabeçalho que chame atenção, corpo que destaque o presente de aniversário e uma chamada clara para ação.
    Utilize os placeholders corretamente e adapte o texto de acordo com as melhores práticas de copywriting.
    Tome cuidado para não inventar informações, utilize apenas os inputs fornecidos.

  expected_output: |
    - Deve conter até 450 caracteres.
    - A mensagem deve ser amigável, clara e otimizada para disparo via WhatsApp.
    - Formatação adequada para WhatsApp com quebras de linha.
    - Alinhamento com o tom de voz {tom_voz} e consideração do público-alvo {publico_alvo}.
    - Utilização correta dos placeholders da mensagem.
    - A mensagem deve possuir as seguintes seções:
        - **Cabeçalho**: Personalize para chamar atenção imediatamente (Ex.: "Feliz aniversário, {{client_first_name}}! 🎉").
        - **Corpo**: Destaque o presente ou benefício de aniversário (Ex.: "Aproveite um presente especial: {{giftback_amount}} de desconto para você.").
        - **Call to Action (CTA)**: Finalize com uma instrução clara (Ex.: "Use o código {{giftback_code}} e aproveite em {{store_url}}").
